version: "3.7"

services:
  # db:
  #   image: postgres
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8001:8000"
    # depends_on:
    #   - db
  food_app:
    container_name: food_app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  food_app_storybook:
    container_name: food_app_storybook
    build:
      context: ./frontend
      dockerfile: Dockerfile-Storybook
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports:
      - "9009:9009"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
